services:
  database:
    image: postgres:17-alpine
    restart: always
    volumes:
      - db_volume:/var/lib/postgres
    env_file:
      - .env
    networks:
      -  db_network
    ports:
      - "5432:5432"

  adminer:
     image: adminer
     restart: always
     networks:
       - db_network
     ports:
       - "8081:8080"

  front-end:
    build: front-end
    restart: always
    env_file:
      - front-end/.env
    networks:
      - app_network
    ports:
      - "8080:80"

  back-end:
    build: back-end
    depends_on:
      - database
    restart: on-failure
    env_file:
      - back-end/.env
    networks:
      - app_network
      - db_network
    ports:
      - "3000:3000"

networks:
  app_network:
  db_network:

volumes:
  db_volume:
